#!docker-compose.yml

services:  
  nginx-ssl-proxy:
    image: nginx-ssl-proxy-test:latest
    restart: always
    environment:
      UPSTREAM_HOST: nvidia.demo.mymap.online
      UPSTREAM_PORT: 443
      UPSTREAM_PROTOCOL: https
      SERVERNAME: ssl-test.mymap.online
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
