#!/usr/bin/with-contenv bash
/usr/local/bin/ep -v /etc/nginx/conf.d/*

if [ "$DO_AUTH" == "required" ]; then
    cp /root/auth* /etc/nginx

    # Set random cookie/password values if not provided
    if [ "x$COOKIE_VALUE" == "x" ]; then
        COOKIE_VALUE=$(pwgen -s -B 25)
        echo Cookie Value: $COOKIE_VALUE
    fi
    if [ "x$PROXY_PASSWORD" == "x" ]; then
        PROXY_PASSWORD=$(pwgen -s -B 25)
        echo Proxy Password: $PROXY_PASSWORD
        echo Proxy Password: $PROXY_PASSWORD > /tmp/proxy_password
    fi
    echo -n "admin:" > /tmp/htpasswd
    echo $PROXY_PASSWORD | openssl passwd -apr1 -stdin >> /tmp/htpasswd

    IPR_EXPANDED=""
    for ip in $WHITELIST_IPS; do
        IPR_EXPANDED="$IPR_EXPANDED $ip \"yes\"; "
    done

    COOKIE_VALUE="$COOKIE_VALUE" IPR_EXPANDED="$IPR_EXPANDED" /usr/local/bin/ep -v /etc/nginx/auth_part*.conf
fi

if [ "$SECURITY_HEADERS" == "skip" ]; then
    echo "" > /etc/nginx/security_headers.conf
fi

echo '' > /etc/nginx/trusted_proxies.conf

if [ "$REAL_IP_RECURSIVE" == "on" ]; then
    echo "real_ip_header X-Forwarded-For;" >> /etc/nginx/trusted_proxies.conf \
    && echo "real_ip_recursive on;" >> /etc/nginx/trusted_proxies.conf
fi

if [ "$SET_REAL_IP_FROM_CLOUDFLARE" == "yes" ]; then
    cat /etc/nginx/cloudflare.conf >> /etc/nginx/trusted_proxies.conf
fi

if [ "$SET_REAL_IP_FROM" != "x" ]; then
    SET_REAL_IP_FROM_EXPANDED=""
    for ip in $SET_REAL_IP_FROM; do
        SET_REAL_IP_FROM_EXPANDED="$SET_REAL_IP_FROM_EXPANDED set_real_ip_from ${ip};"
    done
    echo $SET_REAL_IP_FROM_EXPANDED >> /etc/nginx/trusted_proxies.conf
fi

if [ "$HSTS_HEADER" == "skip" ]; then
    echo "" > /etc/nginx/hsts.conf
elif [ "x$HSTS_HEADER" != "x" ]; then
    echo add_header Strict-Transport-Security \"${HSTS_HEADER}\" always\; > /etc/nginx/hsts.conf
fi

echo '' > /etc/nginx/request_size.conf

if [ "x$NGINX_CLIENT_MAX_BODY_SIZE" != "x" ]; then
    echo client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE}\; >> /etc/nginx/request_size.conf
fi

if [ "x$NGINX_CLIENT_BODY_BUFFER_SIZE" != "x" ]; then
    echo client_body_buffer_size ${NGINX_CLIENT_BODY_BUFFER_SIZE}\; >> /etc/nginx/request_size.conf
fi

if [ ! -e /etc/letsencrypt/fullchain-copy.pem ]; then
    cp /etc/nginx/temp-server-cert.pem /etc/letsencrypt/fullchain-copy.pem
fi

if [ ! -e /etc/letsencrypt/privkey-copy.pem ]; then
    cp /etc/nginx/temp-server-key.pem /etc/letsencrypt/privkey-copy.pem
fi

exec nginx -g 'daemon off;'
